toksubst.sh -i "BQ"     "bq"     parse-build-log.sh
toksubst.sh -i "BS"     "bs"     parse-build-log.sh
toksubst.sh -i "CMD"    "cmd"    parse-build-log.sh
toksubst.sh -i "CN"     "cn"     parse-build-log.sh
toksubst.sh -i "CR"     "cr"     parse-build-log.sh
toksubst.sh -i "DQ"     "dq"     parse-build-log.sh
toksubst.sh -i "FS"     "fs"     parse-build-log.sh
toksubst.sh -i "IFS"    "ifs"    parse-build-log.sh
toksubst.sh -i "LINE"   "line"   parse-build-log.sh
toksubst.sh -i "MF"     "mf"     parse-build-log.sh
toksubst.sh -i "MT"     "mt"     parse-build-log.sh
toksubst.sh -i "MYVARS" "myvars" parse-build-log.sh
toksubst.sh -i "OUTPUT" "output" parse-build-log.sh
toksubst.sh -i "OVS"    "ovs"    parse-build-log.sh
toksubst.sh -i "SQ"     "sq"     parse-build-log.sh
toksubst.sh -i "TS"     "ts"     parse-build-log.sh
toksubst.sh -i "VIFS"   "vifs"   parse-build-log.sh
toksubst.sh -i "VN"     "vn"     parse-build-log.sh
toksubst.sh -i "VS"     "vs"     parse-build-log.sh
toksubst.sh -i "WS"     "ws"     parse-build-log.sh
