ls -d "/cygdrive/c/Sources/Clementine/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/Clementine/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/Clementine/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/Clementine/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/Clementine/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/Clementine/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/android_ndk"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/auto"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/autotools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/make"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/premake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/svn"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/svn_version"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2008-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2008"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2010-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2010"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2012-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2012"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2013-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2015-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT-20150821/build/vs2015"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/android_ndk"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/auto"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/autotools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/make"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/premake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/svn"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/svn_version"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2008-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2008"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2010-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2010"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2012-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2012"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2013-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2015-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/OpenMPT/build/vs2015"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/atk-2.16.0/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/bzip2-cmake-win32/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-2.8.12.2/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc2/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0-rc3/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/i686-w64-mingw32-5.1.0-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake-3.3.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake.fontconfig/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/cmake.fontconfig/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/coreutils-8.15/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/coreutils-8.15/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/curl-7.44.0/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/curl-7.44.0/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/curl-7.44.0¨/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/i686-w64-mingw32-4.8.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/i686-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/i686-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/i686-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2010-win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2010-win64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2012-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2015-win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2015-win64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/x86_64-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/x86_64-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/x86_64-w64-mingw32-5.1.0-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/dirlist/build/x86_64-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freeglut-3.0.0/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-2.6/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/freetype-cmake-win32/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/gdk-pixbuf-2.30.8/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/glib-2.45.4/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/id3lib-3.8.3/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/id3lib-3.8.3/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libarchive-3.1.2/build/autoconf"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libarchive-3.1.2/build/cmake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libarchive-3.1.2/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libarchive-3.1.2/build/pkgconfig"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libdv-1.0.0/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libdv-1.0.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libexpat/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libgpod/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libiconv/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libplist/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/libpng-1.6.18/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/llvm/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lynx2-8-8/build/VS2003"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lynx2-8-8/build/VS2005X"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lynx2-8-8/build/VS2008X"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lynx2-8-8/build/VS6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lynx2-8-8/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2010-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2012-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/lzo-2.09/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/mixxx/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pango-1.36.8/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pcre-8.37/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pic32_pwm_motor_control/build/default"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/pkg-config/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/bc551"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/bc56"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/bc564"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/bc582"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/como4301"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/como433"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/cw7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/cw8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/dm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/gcc32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/gcc33"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/gcc34"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/gcc40"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/icl7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/icl8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/ow12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc10"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc11"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc14"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc42"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc5"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc71"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vc9"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/vecc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14/build/wc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/bc551"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/bc56"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/bc564"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/bc582"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/como4301"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/como433"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/cw7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/cw8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/dm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/gcc32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/gcc33"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/gcc34"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/gcc40"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/icl7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/icl8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/ow12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc42"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc5"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc71"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vc8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/vecc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/recls-1.8.14_orig/build/wc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/transcode-1.1.7/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/transcode-1.1.7/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-cygwin/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw32/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-mingw64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc10/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc11/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc12/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2-vc9/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/wxWidgets-3.0.2/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/c/Sources/zlib-1.2.8/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/Clementine/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/android_ndk"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/auto"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/autotools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/make"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/premake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/svn"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/svn_version"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2008-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2008"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2010-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2010"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2012-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2012"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2013-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2015-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT-20150821/build/vs2015"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/android_ndk"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/auto"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/autotools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/make"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/premake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/svn"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/svn_version"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2008-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2008"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2010-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2010"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2012-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2012"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2013-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2015-ext"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/OpenMPT/build/vs2015"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/atk-2.16.0/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/bzip2-cmake-win32/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-2.8.12.2/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc2/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0-rc3/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/i686-w64-mingw32-5.1.0-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake-3.3.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake.fontconfig/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/cmake.fontconfig/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/coreutils-8.15/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/coreutils-8.15/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/curl-7.44.0/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/curl-7.44.0/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/curl-7.44.0¨/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/i686-w64-mingw32-4.8.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/i686-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/i686-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/i686-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2010-win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2010-win64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2012-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2015-win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2015-win64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/x86_64-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/x86_64-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/x86_64-w64-mingw32-5.1.0-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/dirlist/build/x86_64-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freeglut-3.0.0/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-2.6/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/freetype-cmake-win32/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/gdk-pixbuf-2.30.8/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/glib-2.45.4/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/id3lib-3.8.3/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/id3lib-3.8.3/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libarchive-3.1.2/build/autoconf"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libarchive-3.1.2/build/cmake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libarchive-3.1.2/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libarchive-3.1.2/build/pkgconfig"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libdv-1.0.0/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libdv-1.0.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libexpat/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libgpod/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libiconv/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libplist/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/libpng-1.6.18/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/llvm/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lynx2-8-8/build/VS2003"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lynx2-8-8/build/VS2005X"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lynx2-8-8/build/VS2008X"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lynx2-8-8/build/VS6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lynx2-8-8/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/mingw32-posix-sjlj"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/mingw64-win32-seh"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2010-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2012-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/lzo-2.09/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/mixxx/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pango-1.36.8/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pcre-8.37/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pic32_pwm_motor_control/build/default"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/pkg-config/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/bc551"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/bc56"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/bc564"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/bc582"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/como4301"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/como433"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/cw7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/cw8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/dm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/gcc32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/gcc33"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/gcc34"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/gcc40"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/icl7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/icl8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/ow12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc10"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc11"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc14"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc42"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc5"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc71"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vc9"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/vecc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14/build/wc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/bc551"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/bc56"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/bc564"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/bc582"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/como4301"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/como433"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/cw7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/cw8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/dm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/gcc32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/gcc33"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/gcc34"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/gcc40"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/icl7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/icl8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/ow12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc42"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc5"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc71"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vc8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/vecc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/recls-1.8.14_orig/build/wc12"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/transcode-1.1.7/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/transcode-1.1.7/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-cygwin/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw32/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-mingw64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc10/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc11/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc12/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9-x64/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2-vc9/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/aclocal"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/autoconf_prepend-include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/bakefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/buildbot"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/msw"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/os2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/script"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/tools"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/wxWidgets-3.0.2/build/wince"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2012-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/e/Sources/zlib-1.2.8/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/Clementine/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/Clementine/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LC-meter-16f876a+n3310display/build/htc-16f876a"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LC-meter-16f876a+n3310display/build/htc-876a"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LC-meter-16f876a+n3310display/build/sdcc-"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LC-meter-16f876a+n3310display/build/sdcc-16f876a"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LC-meter-16f876a+n3310display/build/xc8-16f876a"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/LLVM/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/MoSync-gcc/build/gcc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/Python-2.5.6/build/lib.mingw32_nt-6.1-1.0.18(0.48"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/Python-2.5.6/build/temp.mingw32_nt-6.1-1.0.18(0.48"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/STLport-5.2.1/build/Makefiles"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/STLport-5.2.1/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/STLport-5.2.1/build/misc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/STLport-5.2.1/build/test"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/SndObj-2.6.7/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/autoconf-2.64/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/autoconf-2.69/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/automake-1.14.1/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/blackboard/build/build"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/blackboard/build/icons"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/blackboard/build/images"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/boost-jam/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/boost-jam/build/mingw64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/boost-jam/build/msvc2010-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/boost-jam/build/msvc2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/boost-jam/build/msvc2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/bsed/build/cygwin32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/bsed/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/bsed/build/mingw64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/bsed/build/msvc2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chaosircd-cmake/build/vs2008-win64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chaosircd-cmake/build/vs2013-win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chaosircd-cmake/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chaosircd-github/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chromaprint/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/chromaprint/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.4.6/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.4.6/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.6.4/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.6.4/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.6.4/build/msvc2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.8.12.2/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.8.12.2/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.8.12.2/build/msvc2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-2.8.12.2/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-3.1.0/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-3.1.0/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cmake-3.3.0-rc3/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/codeblocks/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/coreutils-8.21/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/coreutils-8.21/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/coreutils-8.23/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/coreutils-8.23/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/coreutils-8.23/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/cproto-4_7e/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/curl-7.39.0/build/cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/curl-7.39.0/build/cygwin64-cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/curl-7.39.0/build/cygwin64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dejavu/build/lib.linux-x86_64-2.7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/detox-1.2.0/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/detox-1.2.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32-4.8.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32-4.9.1"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/i686-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2010-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2013-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2013-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2015-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/vs2015-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-linux-gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-unknown-linux-gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32-4.7.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32-4.9.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32-4.9.1"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32-4.9.2"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32-5.1.0"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/dirlist/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/essentia/build/c4che"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/essentia/build/src"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/file-5.20/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/file-5.22/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gccxml/build/msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gccxml/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gettext-0.19.3/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gettext-0.19.3/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gettext-0.19.3/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glade/build/linux"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glade/build/mingw-w64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glade/build/mswindows"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glib-2.38.2/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glib-2.40.2/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/glib/build/win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gmock-1.7.0/build/cmake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0-1/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0-1/build/x86_64-linux-gnu-debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0-1/build/x86_64-linux-gnu-static"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0-1/build/x86_64-linux-gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0-1/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-1.4.0/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils-svn/build/x86_64-linux-gnu-debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/gputils/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/grep-2.21/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/grub4dos-chenall/build/i486-slackware-linux"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/httplib2-0.7.7/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/jack1/build/cygwin32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/jack1/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/jack1/build/msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/k8json/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/latex2html-2008/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libdwarf/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libechonest/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libgnurx/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libgpod/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libsecret-0.18/build/m4"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libsecret-0.18/build/valgrind"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libstdcxx/build/pipe_debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libstdcxx/build/pipe_release"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libtool-2.4.3-cygwin32/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/libtool-2.4.3/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/lzma-4.32.7/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/lzma-4.32.7/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/lzma-4.32.7/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/madplay-0.15.2b/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/madplay-0.15.2b/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/marsyas/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/marsyas/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mdf2iso/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mdf2iso/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11.0~dfsg.orig/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11.0~dfsg.orig/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11.0~dfsg.orig/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11.0~dfsg.orig/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11.0~dfsg.orig/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.11/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-1.12-git/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master-git/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx-master/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/build-mixxx-Qt4_8_6_mingw482r3_seh-Debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/mingw-x"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/nsis"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/osx"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/qtcreator"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mixxx/build/unused"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mktemp-1.5/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mlton/build/bin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mlton/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mofilereader/build/bin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mpg123-1.22.2/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/mpg123-1.22.2/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ndjbdns-1.06/build/i486-slackware-linux"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ndjbdns-1.06/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ndjbdns-1.06/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/normalize-0.7.7/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/normalize-0.7.7/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/Debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/Debug_static"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/Release"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/Release_static"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/build"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/notepad2-mod/build/cmake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/openlayers/build/closure-compiler"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/openssl-cmake-1.0.1e-src/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/pexports-0.46/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/pexports-0.46/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/pictest/build/htc-16f876a"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/pip-1.5.6/build/bdist.macosx-10.4-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/pip-1.5.6/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/portaudio/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/protobuf/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/protobuf/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/protobuf/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/protobuf/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/puremvc/build/eclipse"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/puremvc/build/mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/puremvc/build/mingw64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/puremvc/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/ar"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/bc56"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/bc582"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/cw8.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/cw8.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/dm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc34.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc34.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc40.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc41.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc42.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc43.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc44.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc45.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/gcc46.unix"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/icl10.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/icl11.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/icl8.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/icl9.win32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc10.unixem"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc10.x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc10"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc6.unixem"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc6"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc71"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc8.unixem"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc8.x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc8"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc9.unixem"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc9.x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/recls-1.9.1-alpha-8/build/vc9"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/QMTest"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/dist"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/doc"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/scons-local"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/scons-src-2.3.4"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/scons-src"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/scons"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-deb"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-local-tar-gz"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-local-zip"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-rpm"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-src-tar-gz"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-src-zip"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-tar-gz"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/test-zip"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/unpack-tar-gz"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/scons/build/unpack-zip"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/i686-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/x86_64-linux-gnu-debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/x86_64-linux-gnu-static"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/x86_64-linux-gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sdcc-3.4.0/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/setuptools-7.0/build/bdist.macosx-10.4-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/setuptools-7.0/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish-build/build/vs2010"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/cmake"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/cygwin32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/make"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/vs2008-x64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/vs2008-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/shish/build/vs2013"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/bin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/examples"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/include"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/plumhall"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/rwtest"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stdcxx/build/tests"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stx-btree/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stx-btree/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/stx-btree/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-0.9.7/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-0.9.7/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-git/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-git/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-old/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils-old/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utils/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utilsold/build/debian"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/sw-utilsold/build/gnu"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/tar-1.28/build/i686-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/tar-1.28/build/x86_64-pc-cygwin"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search/build/lib.linux-x86_64-2.7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search/build/scripts-2.7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search_0.11.2/build/lib.linux-x86_64-2.7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search_0.11.2/build/lib"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/torrent-search_0.11.2/build/scripts-2.7"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ustl-git/build/debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ustl-git/build/pipe_debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ustl-git/build/pipe_release"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ustl-git/build/release"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/ustl/build/pipe_debug"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/util-linux-2.25.2/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/waf/build/c4che"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/linux"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc10-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc10-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc11-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc11-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc12-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc12-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc9-x86"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/vc9-x86_64"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/x265/build/xcode"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/xz-5.2.1/build/i686-pc-msys"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/yasm/build/cygwin32"/{Makefile,*.sln} 2>/dev/null
ls -d "/cygdrive/l/Sources/zlib-1.2.8/build/x86_64-w64-mingw32"/{Makefile,*.sln} 2>/dev/null
