LANG=en_US
LC_ALL=C
LC_CTYPE=en_US.ISO-8859-1
HISTFILESIZE=16777216
HISTSIZE=94208
XLIB_SKIP_ARGB_VISUALS=1
LESS="-R"
HISTFILESIZE=$((HISTSIZE * 512))
export LC_ALL LC_CTYPE LANG HISTSIZE HISTFILESIZE XLIB_SKIP_ARGB_VISUALS LESS LS_COLORS TERM
export LS_COLORS
