#!/bin/sh
PIPE_TOOL=$MOSYNCDIR/bin/pipe-tool

unset ARGS
while :; do
  case "$1" in
    -o) OUTPUT="$2"; shift 2 ;; -o*) OUTPUT="${1#-o}"; shift ;;
    -L) LIBDIRS="$LIBDIRS $2"; shift 2 ;; -L*) LIBDIRS="$LIBDIRS ${2#-L}"; shift ;;
    -l) LIBS="$LIBS $2"; shift 2 ;; -l*) LIBS="$LIBS ${2#-l}"; shift ;;
    --heap) HEAPSIZE="$2"; shift 2 ;;
    --stack) STAKSIZE="$2"; shift 2 ;;
    -z) case "$2" in
      stacksize=*) STACKSIZE=${2#*=} ;;
      heapsize=*) HEAPSIZE=${2#*=} ;;
    esac
    shift 2
    ;;
    *.lib) LIBS="$LIBS ${1%.*}"; shift ;;
    *) ARGS="${ARGS+$ARGS }$1"; shift ;;
  esac
done

OPTS="-appcode=YSYW -stabs=stabs.tab -heapsize=${HEAPSIZE-3145728} -stacksize=${STACKSIZE-524288} -datasize=${DATASIZE-4194304} -sld=sld.tab"

for LIBDIR in $LIBDIRS; do
  OPTS="$OPTS -s${LIBDIR}"
done

OPTS="$OPTS -B ${OUTPUT-a.out}"

for LIB in $LIBS; do
  ARGS="${ARGS+$ARGS }${LIB}.lib"
done
set -x
exec "$PIPE_TOOL" $OPTS $ARGS
